-- 코드를 작성해주세요
SELECT YEAR(AP.YM) AS YEAR, 
ROUND(AVG(AP.PM_VAL1), 2) AS PM10, 
ROUND(AVG(AP.PM_VAL2), 2) AS `PM2.5` 
FROM AIR_POLLUTION AP
WHERE AP.LOCATION2 = '수원'
GROUP BY YEAR(AP.YM)
ORDER BY YEAR ASC;