-- 코드를 입력하세요
SELECT PR.PRODUCT_CODE, S.SM * PR.PRICE AS SALES
FROM PRODUCT AS PR
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SM
        FROM OFFLINE_SALE AS OT
        GROUP BY OT.PRODUCT_ID) AS S ON S.PRODUCT_ID = PR.PRODUCT_ID 
ORDER BY SALES DESC, PR.PRODUCT_CODE ASC;