-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) as YEAR, MONTH(OS.SALES_DATE) as MONTH, UI.GENDER as GENDER, count(DISTINCT UI.USER_ID) as USERS
FROM ONLINE_SALE AS OS INNER JOIN USER_INFO AS UI ON OS.USER_ID = UI.USER_ID 
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER 
ORDER BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER;