-- 코드를 입력하세요
SELECT CAR.CAR_TYPE, COUNT(*) AS CARS FROM CAR_RENTAL_COMPANY_CAR AS CAR 
WHERE CAR.OPTIONS LIKE '%통풍시트%' OR CAR.OPTIONS LIKE '%열선시트%' OR CAR.OPTIONS LIKE '%가죽시트%'
GROUP BY CAR.CAR_TYPE
ORDER BY CAR.CAR_TYPE;