-- 코드를 입력하세요
SELECT MP.MEMBER_ID, MP.MEMBER_NAME, MP.GENDER, DATE_FORMAT(MP.DATE_OF_BIRTH,'%Y-%m-%d')
FROM MEMBER_PROFILE AS MP 
WHERE MP.TLNO IS NOT NULL AND MONTH(MP.DATE_OF_BIRTH) = 3 AND MP.GENDER = 'W' 
ORDER BY MP.MEMBER_ID;