-- 코드를 입력하세요

-- SELECT * FROM ANIMAL_OUTS ORDER BY HOUR(DATETIME)
SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT FROM ANIMAL_OUTS AS AO 
WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) <= 19 
GROUP BY HOUR 
ORDER BY HOUR
